[tool.poetry]
name = "server"
version = "0.1.0"
description = ""
authors = ["Denis Khmyrov <denis.e.khmyrov@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
asyncpg = "^0.29.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
